#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"
# (ext_op_hex, name)
PROBES=(
  "10|SppExtCarMode"
  "11|SECOND_SET_KEY_PIC"
  "12|SECOND_SET_KEY_FUNC"
  "13|SECOND_SET_GIF_TYPE"
  "14|SECOND_SET_USER_DEFINE_TIME"
  "15|SECOND_GET_USER_DEFINE_TIME"
  "16|SECOND_CLEAR_USER_DEFINE_INDEX"
  "17|SECOND_USE_USER_DEFINE_INDEX"
  "18|SECOND_GET_NEW_POWER_ON_CHANNEL"
  "19|SECOND_SET_SAVE_VOLUME_CFG"
  "1a|SECOND_SET_AUTO_CONNECT_CFG"
  "1b|SECOND_SET_GIF_PLAY_TIME_CFG"
  "1c|SECOND_SET_MUSIC_NAME_CFG"
  "1d|SECOND_RECORD_CTRL"
  "1e|SECOND_KARAOKE_CTRL"
  "21|SECOND_TOUCH"
  "20|SECOND_WIRELESS_MIC_CTRL"
  "23|SECOND_SET_SCREEN_DIR_CFG"
  "24|SECOND_SET_SCREEN_MIRROR_CFG"
  "25|SECOND_CLEAR_SYS_CFG"
  "26|SECOND_SET_LANGUAGE"
  "27|SECOND_SUPPORT_MORE_ANCS"
  "28|SECOND_GET_DECODE_FILE_INFO"
  "29|SECOND_GET_NORMAL_FILE_INFO"
  "2a|SECOND_GET_CLOCK_ID_INFO"
  "2b|SECOND_GET_DEVICE_INFO"
  "2c|SECOND_DEVICE_FORMAT_FLAG"
  "2d|SECOND_GET_FONT_INFO"
  "2e|GET_SYSTEM_TIME"
  "2f|SECOND_OPEN_SCREEN_CTRL"
  "30|SECOND_GET_ZSTD_DECODE_FILE_INFO"
  "31|SECOND_APP_SEND_GIF_START"
  "32|SECOND_SEND_DEVICE_EQUALIZER_CTRL"
  "33|SECOND_SEND_DEVICE_LIGHT_EFFECT_CTRL"
  "34|SECOND_APP_SET_VOL"
  "35|SECOND_APP_GET_VOL"
  "36|SECOND_APP_SET_MUSIC_PLAY_PAUSE"
  "37|SECOND_GET_EZIP_DECODE_FILE_INFO"
  "38|SECOND_GET_EZIP_ROTATE_DECODE_FILE_INFO"
  "3a|SECOND_GET_JPEG_PIXEL_FILE_INFO"
)
: > /tmp/divoom-send.log
for entry in "${PROBES[@]}"; do
  IFS='|' read -r op name <<< "$entry"
  echo "--- ext 0x$op $name ---"
  ./dv raw bd "$op" 00
  sleep 0.7
done
